/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@Entry
@Component
export struct MainTitleBar {
  build() {
    Column() {
      Text('看新闻')
        .fontSize('20fp')
        .margin({
          left: '24',
          right: '24',
          top: '12'
        })
    }
    .width('100%')
    .constraintSize({ minHeight: '45' })
    .alignItems(HorizontalAlign.Start)
    .backgroundColor($r('app.color.colorSubBackground'))
  }
}
