/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  SwiperModel, PhoneTypeModel, ShowImgModel, RecommendDataModel, GoodsInfoModel, ListDataModel
} from "../model/detailModel"

export const swiperData: Array<SwiperModel> = [
  { src: "/resources/detailImg/swiper/swiper1.png" },
  { src: "/resources/detailImg/swiper/swiper2.png" },
  { src: "/resources/detailImg/swiper/swiper3.png" },
]

export const phoneTypeData: Array<PhoneTypeModel> = [
  {
    uri: "/resources/detailImg/deliver/deliver_type1.png",
    color: "亮黑色"
  },
  {
    uri: "/resources/detailImg/deliver/deliver_type2.png",
    color: "星河银"
  },
  {
    uri: "/resources/detailImg/deliver/deliver_type3.png",
    color: "翡翠冷"
  },
  {
    uri: "/resources/detailImg/deliver/deliver_type4.png",
    color: "紫罗兰",
  },
  {
    uri: "/resources/detailImg/deliver/deliver_type5.png",
    color: "丹霞橙"
  }
]

export const showImgData: Array<ShowImgModel> = [
  { uri: "/resources/detailImg/evaluation/buyersShow1.png" },
  { uri: "/resources/detailImg/evaluation/buyersShow2.png" },
  { uri: "/resources/detailImg/evaluation/buyersShow3.png" },
  { uri: "/resources/detailImg/evaluation/buyersShow4.png" },
]

export const recommendData: Array<RecommendDataModel> = [
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg1.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg2.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg3.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg4.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg5.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg6.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  }
]

export const goodsInfoData: Array<GoodsInfoModel> = [
  {
    img: "/resources/detailImg/recommendImg/attention/list_1.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_1.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_2.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_3.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_4.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_4.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_6.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_6.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_6.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_6.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_4.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_6.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_4.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_5.png"
  },
  {
    img: "/resources/detailImg/recommendImg/attention/list_6.png"
  },
]

export const listData: Array<ListDataModel> = [
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg1.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg2.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg3.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg4.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg5.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg6.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg7.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg8.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg9.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg10.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg1.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg2.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg3.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg4.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg5.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg6.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg7.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg8.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg9.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg10.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg1.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg2.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg3.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg4.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg5.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg6.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg7.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg8.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg9.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg10.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg1.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg2.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg3.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg4.png',
    title: 'XX Mate 40 5G 全网通',
    price: '￥196'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg5.png',
    title: 'XX手机 大多数人的选择',
    price: '￥339.98'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg6.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
  {
    img: '/resources/detailImg/recommendImg/recommendImg/recommendImg7.png',
    title: 'XX Mate 40 Pro 5G 全网通',
    price: '￥188'
  },
]