/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ExampleDataModel, SearchDataModel } from '../model/searchModel'

export const exampleData: Array<ExampleDataModel> = [
  { "exampleText": "精品好礼" },
  { "exampleText": "品牌手机" },
  { "exampleText": "节日大优惠" },
  { "exampleText": "学生背包" },
  { "exampleText": "零食" },
  { "exampleText": "手机壳" },
  { "exampleText": "毛绒玩具" },
  { "exampleText": "行李箱" },
]

export const searchData: Array<SearchDataModel> = [
  { "searchData": "XX" },
  { "searchData": "商品" },
  { "searchData": "XX手机" },
  { "searchData": "微商" },
  { "searchData": "5G手机" },
  { "searchData": "成品好衣" },
  { "searchData": "视频" },
  { "searchData": "XX品牌手机" },
  { "searchData": "精品手机" },
  { "searchData": "羽绒服" },
  { "searchData": "图片" },
  { "searchData": "精品好礼" },
  { "searchData": "品牌手机" },
  { "searchData": "节日大优惠" },
  { "searchData": "双肩包" },
  { "searchData": "零食" },
  { "searchData": "手机壳" },
  { "searchData": "毛绒玩具" },
  { "searchData": "行李箱" }
]